extends: ["google", "plugin:security/recommended"]
plugins:
  ["security"]
env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 9
  ecmaFeatures:
    arrowFunctions: true
    destructuring: true
  sourceType: "module"
rules:
  arrow-parens: ["error", 2]
  indent: ["error", 2]
  max-len: ["error", 100, 2]
  quotes: ["error", "double"]

